#!/bin/bash

# Create necessary directories
mkdir -p /opt/demo-server/html
mkdir -p /opt/demo-server/bash-scripts

# Set permissions
chown -R root:root /opt/demo-server
chmod -R 755 /opt/demo-server


# Ask the user for a port number
echo "Please enter the port number for the demo-server service:"
read PORT

# Validate the port number
if ! [[ "$PORT" =~ ^[0-9]+$ ]] || [ "$PORT" -lt 1024 ] || [ "$PORT" -gt 65535 ]; then
    echo "Invalid port: $PORT. Please enter a number between 1024 and 65535."
    exit 1
fi

# Write the port number to the configuration file
echo "Port selected: $PORT"
echo "port=$PORT" > /opt/demo-server/html/server.conf

# Copy the systemd service file
cp /opt/demo-server/demo-server.service /etc/systemd/system/

# Reload systemd and enable the service
systemctl daemon-reload
systemctl enable demo-server.service
systemctl start demo-server.service


echo "Installation of demo-server is complete."

echo "To finalize the installation, please follow these steps:"
echo "1. Make the brski installation script executable:"
echo "   sudo chmod +x /opt/demo-server/bash-scripts/install_brski.sh"
echo "2. Run the brski installation script:"
echo "   sudo /opt/demo-server/bash-scripts/install_brski.sh"
